version: '3'

services:
  app:
    build: ./docker/go
    container_name: golang
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./src:/go/src/work
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app